import type { Metadata } from "next";
import { Roboto, Outfit } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
   subsets: ["latin"],
   weight: ["100", "300", "400", "500", "700", "900"],
   variable: "--font-roboto",
});
const outfit = Outfit({
   subsets: ["latin"],
   variable: "--font-outfit",
});

export const metadata: Metadata = {
   title: "Krypto Next",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={`${roboto.variable} ${outfit.variable}`}>
            {children}
         </body>
      </html>
   );
}
